### ISSUE TITLE
fix fontsize in download area

### ISSUE THREAD

**Issue by ThatsNasu** [ThatsNasu/Fiae-DE#81]
download main page is fine, but selecting a subcategory (resulting in landing on intermediate page)  results in having a fontsize big enough to view it from miles away.

**Comment by netcodedev** [comment]
Change h1 to h2 in https://github.com/DasNasu/Fiae-DE/blob/2cf2d760d6b3161dc5f727cf5c3e4f3592b236c4/pages/Downloads.php#L14-L18

**Comment by ThatsNasu** [comment]
wtf? comment? why not commit / PR?
