### ISSUE TITLE
Wrong message on login after failed login

### ISSUE THREAD

**Issue by netcodedev** [ThatsNasu/Fiae-DE#9]
**Describe the bug**
When successfully logging in after a failed attempt the wrong message is shown in content

**To Reproduce**
1. fail a login attempt
2. Login using correct credentials

**Expected behavior**
The message should say you successfully logged in

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - Browser Chrome 
 - Version 94

**Comment by ThatsNasu** [comment]
Fixed the condition checks
